---
sudo: required
dist: bionic
language: python
python:
  - "3.7"
services:
  - postgresql
addons:
  postgresql: '9.6'
jobs:
  include:
  - stage: test
    before_script: psql -U postgres 'CREATE EXTENSION "uuid-ossp";'
    script: echo 1
